language: scala
dist: trusty
sudo: false
jdk:
- openjdk8
- oraclejdk9
scala:
- 2.11.12
- 2.12.4
sudo: false
script: .ci/build.sh
after_success: bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
